services:
    nginx:
        image: nginx:latest
        container_name: edu_nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
            - ./logs/nginx:/var/www/logs/nginx
            - .:/var/www
        links:
            - php
    php:
        build:
            dockerfile: ./_docker/php/Dockerfile
        container_name: edu_php
        working_dir: "/var/www"
        volumes:
            - .:/var/www
            - ./_docker/php/php.ini:/usr/local/etc/php/conf.d/40-custom.ini
            - ./_docker/php/xdebug.ini:/etc/php/8.3/fpm/conf.d/xdebug.ini
        user: "1000:1000"
        environment:
            - XDEBUG_CONFIG=remote_host=host.docker.internal
    postgres:
        container_name: edu_postgres
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_PORT=${DB_PORT}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - ./_docker/postgres/data:/var/lib/postgresql/data
    #            - ./.docker/conf/postgres/:/docker-entrypoint-initdb.d/
